/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: CarTypeService.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./CarTypeService_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.CarTypeServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.CarTypeServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CarTypeRequest,
 *   !proto.CarTypeResponse>}
 */
const methodDescriptor_CarTypeService_AddNewCarType = new grpc.web.MethodDescriptor(
  '/CarTypeService/AddNewCarType',
  grpc.web.MethodType.UNARY,
  proto.CarTypeRequest,
  proto.CarTypeResponse,
  /**
   * @param {!proto.CarTypeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CarTypeResponse.deserializeBinary
);


/**
 * @param {!proto.CarTypeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CarTypeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CarTypeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CarTypeServiceClient.prototype.addNewCarType =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/CarTypeService/AddNewCarType',
      request,
      metadata || {},
      methodDescriptor_CarTypeService_AddNewCarType,
      callback);
};


/**
 * @param {!proto.CarTypeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CarTypeResponse>}
 *     Promise that resolves to the response
 */
proto.CarTypeServicePromiseClient.prototype.addNewCarType =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/CarTypeService/AddNewCarType',
      request,
      metadata || {},
      methodDescriptor_CarTypeService_AddNewCarType);
};


module.exports = proto;

